### ISSUE TITLE
Posting just the Permalink

### ISSUE THREAD

**Issue by ghost** [pjv/nostrtium#2]
First off , thanks for creating this!
Installed it this evening and the plugin is working perfectly for me under PHP 8.2
My site is private so I would like the option to automatically send just the post's permalink , basically using NOSTR as a simple notification system.
I use the [Share on Mastodon](https://jan.boddez.net/wordpress/share-on-mastodon) plugin to post to the [Fediverse](https://mas.to/@markwaters) in this way , and would love the same functionality on NOSTR.
Thanks for considering.
Mark.

**Comment by pjv** [comment]
Hi, glad the plugin is working for you. I hope I’ll have some time to dig into my todo list for it soon.

Are you asking for a setting that would auto-publish (to nostr) the permalink of every wordpress post upon publication?

**Comment by ghost** [comment]
Yep , just a simple URL , automatically , like this - [https://mas.to/@markwaters](https://mas.to/@markwaters)
If a few coffees :coffee: will help , send me a lightning invoice :zap: 
Thanks
Mark.

**Comment by pjv** [comment]
@markwaters If you can, please test version 0.7.0-beta.1 from the [releases page](https://github.com/pjv/nostrtium/releases) (here at github).

There are new auto-publish options on the settings page.

Note that after updating the plugin (just this one time) you will need to re-enter your private key on the settings page.

**Comment by ghost** [comment]
Hey @pjv 
Sorry for the delay , was AFK.
I have replaced the previous version with this new version , but cannot activate it.
Seeing 'The “Nostrtium” plugin cannot run without the wp-content/uploads directory being writeable.' despite recursively chmod 777'ing the wp-content/ directory.

**Comment by pjv** [comment]
thanks for the report @markwaters 

i took a guess and made a tweak and uploaded 0.7.0-beta.2 to github. See if that version lets you activate.

**Comment by ghost** [comment]
Replaced the previous plugin code completely.
Now seeing this fatal error.
'Plugin could not be activated because it triggered a fatal error.'

```
Warning: require_once(/var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium//vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/nostrtium.php on line 38

Fatal error: Uncaught Error: Failed opening required '/var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium//vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/nostrtium.php:38 Stack trace: #0 /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-admin/includes/plugin.php(2314): include_once() #1 /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-admin/plugins.php(192): plugin_sandbox_scrape() #2 {main} thrown in /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/nostrtium.php on line 38
```

**Comment by pjv** [comment]
@markwaters thanks for trying these. They are all working for me on my dev and test systems (as well as one production system), so it’s very useful to have a report from another setup where it’s not working. I just uploaded beta.3 to the releases page that hopes to fix that fatal error…

**Comment by ghost** [comment]
No worries @pjv , not sure why I am having so many issues , not had problems like this before.
I think I am still having the same errors.

```
Warning: require_once(/var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/nostrtium.php on line 38

Fatal error: Uncaught Error: Failed opening required '/var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/nostrtium.php:38 Stack trace: #0 /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-admin/includes/plugin.php(2314): include_once() #1 /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-admin/plugins.php(192): plugin_sandbox_scrape() #2 {main} thrown in /var/www/mwaters7eu2pyfcz36oehlc3htnqarakd7meeyz4lvbubff64ethxzqd.onion/wp-content/plugins/nostrtium/nostrtium.php on line 38

```

**Comment by pjv** [comment]
@markwaters I just tried installing beta.3 downloaded from github on a working wordpress install and it seemed to work fine. Just guessing but based on that error (missing a file that is definitely in the zip file in the release) it could be due to the method you are using to install.

If you are not doing it like this, try downloading nostrtium.zip (not the source code archives because those ARE missing stuff including the file that is causing your fatal error) from the releases page:

<img width="546" alt="SCR-20230604-ixsd" src="https://github.com/pjv/nostrtium/assets/327716/3477ac2c-d37f-4a1d-b7f2-1c434026a488">

…and then go to the `/wp-admin/plugin-install.php` page on your site and click “upload plugin” and then upload nostrtium.zip from that page:
<img width="659" alt="SCR-20230604-iylf" src="https://github.com/pjv/nostrtium/assets/327716/c07c1dbb-560d-44bc-b662-42163b00561c">

**Comment by ghost** [comment]
Thanks @pjv 
I was downloading the .tar.gz file on the server , unpacking into the previously emptied directory , resetting file permissions and restarting the nginx / php stack.
But your way of downloading the zip file directly and uploading it is much easier , and works!
No errors this time.
Woohoo!

**Comment by ghost** [comment]
Tested , working.
Thanks so much!
Do you have a lightning address @pjv ?

**Comment by pjv** [comment]
Thanks for the report.

Just as an FYI, it’s pretty common for a “build artifact” (like nostrtium.zip in the releases here) to be different from the source code archives which are only useful if you are going to develop and build the plugin on your own. Many times wordpress plugins don’t involve a build process and the source code and the plugin are the same. But in this case (and in most cases where the plugin includes a “vendor” directory or you see any “composer” related files) the plugin is the result of a build process that puts stuff into it that doesn’t exist in the source code in the repo.
