### ISSUE TITLE
Multiple Posts freakout

### ISSUE THREAD

**Issue by ghost** [pjv/nostrtium#3]
Yesterday my PHP 8.2 got upgraded from 8.2.6 to 8.2.7.
I also changed some of the NOSTR relays but I don't think this was related.
When I posted publicly ( so the post would be sent out to NOSTR , private posts aren't sent ), Wordpress freaked out by created multiple posts, in batches of six I think.
These posts were all identical in Wordpress except the URL.
The post creating process didn't stop until I restarted PHP / nginx.
I switched back to the previous version of PHP , version 8.1.20 but this did the same.
I disabled the Nostrtium plugin and have had no freakout since.

I have the nginx error logs which contain more information , happy to send them over privately.

This morning I have installed php8.2-bcmath , meanwhile php8.2-gmp was already installed.
Re-enabled plugin and no longer seeing the freakout.

**Comment by pjv** [comment]
Thanks for the report and for posting the error log in the other issue. I can probably fix the error you sent. If there are more logs that seem worthwhile and you want to send them privately, I just enabled a setting in this repo that lets you privately report security vulnerabilities. Maybe bending the definition of a vulnerability a little bit, but try it and see if it lets you attach whatever logs seem relevant. Look in the “Security” tab above.

**Comment by pjv** [comment]
Hoping this is fixed with v0.7.2

**Comment by ghost** [comment]
Thanks @pjv
