### ISSUE TITLE
Unable to add Tor Hidden Service hosted relay

### ISSUE THREAD

**Issue by ghost** [pjv/nostrtium#6]
I am unable to add an unencrypted Tor Hidden Service hosted relay URL to the list.

e.g. ws://relayaddressisverylongurl.onion

It looks like it is possible in the PHP code , but the javascript checking doesn't allow it.
Sorry , I am not a programmer.

**Comment by pjv** [comment]
@markwaters I changed the url validation so it doesn’t require wss (SSL), but i have no examples of unencrypted relays to test against so i don’t know how the php nostr library I'm using will respond. When you have a chance, can you install the beta I posted here: https://github.com/pjv/nostrtium/releases/tag/v0.7.3-beta.1 and let me know if it works ok?

**Comment by ghost** [comment]
Tested , and working perfectly.
Here is the log from my Tor hidden service relay receiving the post.

```
Jun 22 19:00:27 relay strfry[617]: 2023-06-22 19:00:27.366 (31669.864s) [Websocket       ]INFO| [53] Connect from 127.0.0.1 compression=N sliding=N
Jun 22 19:00:27 relay strfry[617]: 2023-06-22 19:00:27.370 (31669.868s) [Writer          ]INFO| Inserted event. id=493d0d49c6c7a107ec6b050d17e1167dd40ee4a99631f2e9f9c013fcb79034b3 levId=65
Jun 22 19:00:27 relay strfry[617]: 2023-06-22 19:00:27.370 (31669.869s) [Websocket       ]INFO| [53] Disconnect from 127.0.0.1 UP: 81b (0.0% compressed) DN: 430b (0.0% compressed)
```

Thanks @pjv
